### ISSUE TITLE
PredCRP.pl overwrites input file with last line of content 

### ISSUE THREAD

**Issue by sahhey** [NctuICLab/PredCRP#1]
When running PredCRP.pl on the example files provided here on GitHub I get the following error message: 

_# of CRPBS: 
Argument "" isn't numeric in numeric eq (==) at PredCRP.pl line 56.
No header in input file_

and the input file used (here CRPBS_23weak_before.csv) is turned into CRPBS_23weak_after.csv (see file). The name of the file does not change - I just edited it here for an easier understanding of the problem. 

What can I do to fix it? 

[CRPBS_23weak_before.csv](https://github.com/NctuICLab/PredCRP/files/7466633/CRPBS_23weak_before.csv)
[CRPBS_23weak_after.csv](https://github.com/NctuICLab/PredCRP/files/7466634/CRPBS_23weak_after.csv)

**Comment by mingjutsai** [comment]
Hi,
Thanks for providing this issue. This function was fixed, so you can update this repo and try it again.
